using DinkToPdf;
using DinkToPdf.Contracts;
using Healthcare_And_Wellness.Data;
using Healthcare_And_Wellness.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;


namespace Healthcare_And_Wellness.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly ManagementContext _context;
        private readonly IConverter _converter;

        public ArticlesController(ManagementContext context, IConverter converter)
        {
            _context = context;
            _converter = converter;
        }

        private void PopulateViewBag()
        {
            ViewBag.Username = HttpContext.Session.GetString("Username");
            ViewBag.Role = HttpContext.Session.GetString("Role");
        }

        public IActionResult Index()
        {
            PopulateViewBag();
            var articles = _context.Articles.OrderByDescending(a => a.PublishedDate).ToList();
            return View(articles);
        }

        public IActionResult Create()
        {
            PopulateViewBag();
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Index");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Article article)
        {
            PopulateViewBag();
            if (ModelState.IsValid)
            {
                _context.Articles.Add(article);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        public IActionResult Edit(int id)
        {
            PopulateViewBag();
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Index");

            var article = _context.Articles.Find(id);
            if (article == null) return NotFound();
            return View(article);
        }

        [HttpPost]
        public IActionResult Edit(Article article)
        {
            PopulateViewBag();
            if (ModelState.IsValid)
            {
                _context.Articles.Update(article);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        public IActionResult Delete(int id)
        {
            PopulateViewBag();
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Index");

            var article = _context.Articles.Find(id);
            if (article == null) return NotFound();
            return View(article);
        }

        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            PopulateViewBag();
            var article = _context.Articles.Find(id);
            if (article != null)
            {
                _context.Articles.Remove(article);
                _context.SaveChanges();
                _context.ChangeTracker.Clear();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            PopulateViewBag();
            var article = _context.Articles.Find(id);
            if (article == null) return NotFound();
            return View(article);
        }

        public IActionResult DownloadPdf(int id)
        {
            PopulateViewBag();
            var article = _context.Articles.Find(id);
            if (article == null)
                return NotFound();
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(50);
                    page.Size(PageSizes.A4);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(14));

                    page.Header()
                        .Text($"Healthcare & Wellness: {article.Title}")
                        .SemiBold().FontSize(20).FontColor(Colors.Blue.Medium);

                    page.Content()
                        .PaddingVertical(10)
                        .Column(col =>
                        {
                            col.Item().Text($"Published on: {article.PublishedDate.ToString("MMMM dd, yyyy")}").FontSize(12).FontColor(Colors.Grey.Darken1);
                            col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                            col.Item().Text(article.Content).FontSize(14).LineHeight(1.5f);
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by Smart Medical Helpers").FontSize(10).FontColor(Colors.Grey.Darken1);
                });
            });
            var pdfBytes = document.GeneratePdf();
            return File(pdfBytes, "application/pdf", $"{article.Title}.pdf");
        }
    }
}
